### ISSUE TITLE
Problema con las guest additions

### ISSUE THREAD

**Issue by ornellaolivastri** [sisoputnfrba/tp0#12]
El problema es que sigo todos los pasos que aparecen en este video https://www.youtube.com/watch?v=uMoO58tPc5c pero al reiniciar la vm no realiza la adaptación de tamaño de la ventana. En la terminal me aparecen mensajes de que la instalación concluyó bien y que se necesitaba reiniciar el sistema para aplicar los cambios, pero esto no funcionó. Reinicié varias veces la vm sin obtener el resultado esperado. 
Nota: tengo la version 5.4 de VirtualBox

**Comment by ornellaolivastri** [comment]
Pude hacerlas funcionar finalmente cerrando sesión con la pantalla maximizada y volviendo a abrir, como se indica acá https://github.com/sisoputnfrba/foro/issues/2015.

**Comment by RaniAgus** [comment]
@ornellaolivastri para la próxima: los ayudantes tenemos centralizadas las consultas en https://github.com/sisoputnfrba/foro , ya que de esa forma es más fácil para nosotros revisar ese repo y estar al tanto de las consultas que surjan, además de que ustedes pueden utilizar el buscador para encontrar issues relacionados y encontrarlos todos. ¡Saludos!
