### ISSUE TITLE
Lectura inválida en send_md5()

### ISSUE THREAD

**Issue by ivanpuchalka** [sisoputnfrba/tp0#15]
https://github.com/sisoputnfrba/tp0/blob/0a3f4545550b36477bb5803164e6a756c6d4f770/tp0.c#L204

La llamada a `strlen(content)` puede provocar una lectura inválida, porque `content` no es un string, sino una secuencia de bytes. `send_md5()` debería recibir la longitud del contenido obtenida en `wait_content()` para usar como argumento en `MD5_Update()`, en lugar de `strlen(content) + 1`.

**Comment by tferraro** [comment]
Buenas!

Lo que decís, es **casi** del todo correcto. Content, como se lo recibe del servidor en `wait_content(1)`, es un stream de datos. Sin embargo, en esa misma sección el enunciado reza:
> Nota: es importante tener en cuenta que el servidor enviará un string como dato pero no incluirá ‘\0’ al final. El proceso deberá agregarlo para que el MD5 coincida.

Esto implica que en `wait_content(1)` es necesario convertir el stream a un string y que el content que recibe `send_MD5` _debe ser un string_ :slightly_smiling_face: 

Saludos!
Tom

**Comment by ivanpuchalka** [comment]
Buen día!

El problema era que, agregando el '\0' para convertir el contenido en un string, el MD5 "no coincidía". Resulta que, en realidad, la interpretación de la confirmación del servidor estaba invertida, pero es porque el mismo comentario del código lo da al revés.

`	int result = 1; // Dejemos creado un resultado por defecto`
`	/*
	 19.   Ahora nos toca recibir la confirmacion del servidor.
	 Si el resultado obvenido es distinto de 0, entonces hubo un error
	 */`

El documento del enunciado sí explica el protocolo correctamente.

Saludos

**Comment by ivanpuchalka** [comment]
Dale, ya lo hago.
